2023-02-15 01:03:04.680 [error] <0.467.0>@vmq_ranch_config:reconfigure_listeners_for_type:{269,13} can't reconfigure mqtts listener({127,0,0,1}, 1883) with Options [{max_connections,10000},{nr_of_acceptors,10},{mountpoint,[]},{depth,1},{eccs,[sect571r1,sect571k1,secp521r1,brainpoolP512r1,sect409k1,sect409r1,brainpoolP384r1,secp384r1,sect283k1,sect283r1,brainpoolP256r1,secp256k1,secp256r1,sect239k1,sect233k1,sect233r1,secp224k1,secp224r1,sect193r1,sect193r2,secp192k1,secp192r1,sect163k1,sect163r1,sect163r2,secp160k1,secp160r1,secp160r2]},{require_certificate,false},{tls_version,'tlsv1.2'},{use_identity_as_username,false},{allowed_protocol_versions,[3,4,131]},{allow_anonymous_override,false}] due to {already_started,<0.468.0>}
2023-02-15 01:04:15.137 [error] <0.227.0> Supervisor vmq_swc_store_sup_meta1 had child {vmq_swc_db_leveldb,meta1} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta1/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:04:15.137 [error] <0.228.0> CRASH REPORT Process <0.228.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta1/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:05:15.241 [error] <0.331.0> Supervisor vmq_swc_store_sup_meta2 had child {vmq_swc_db_leveldb,meta2} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta2/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:05:15.242 [error] <0.332.0> CRASH REPORT Process <0.332.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta2/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:06:15.348 [error] <0.356.0> Supervisor vmq_swc_store_sup_meta3 had child {vmq_swc_db_leveldb,meta3} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta3/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:06:15.348 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta3/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:07:15.453 [error] <0.376.0> Supervisor vmq_swc_store_sup_meta4 had child {vmq_swc_db_leveldb,meta4} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta4/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:07:15.453 [error] <0.377.0> CRASH REPORT Process <0.377.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta4/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:08:15.554 [error] <0.387.0> Supervisor vmq_swc_store_sup_meta5 had child {vmq_swc_db_leveldb,meta5} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta5/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:08:15.554 [error] <0.388.0> CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta5/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:09:15.648 [error] <0.397.0> Supervisor vmq_swc_store_sup_meta6 had child {vmq_swc_db_leveldb,meta6} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta6/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:09:15.648 [error] <0.398.0> CRASH REPORT Process <0.398.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta6/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:10:15.760 [error] <0.411.0> Supervisor vmq_swc_store_sup_meta7 had child {vmq_swc_db_leveldb,meta7} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta7/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:10:15.760 [error] <0.412.0> CRASH REPORT Process <0.412.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta7/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:11:15.841 [error] <0.421.0> Supervisor vmq_swc_store_sup_meta8 had child {vmq_swc_db_leveldb,meta8} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta8/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:11:15.841 [error] <0.422.0> CRASH REPORT Process <0.422.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta8/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:12:15.987 [error] <0.432.0> Supervisor vmq_swc_store_sup_meta9 had child {vmq_swc_db_leveldb,meta9} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta9/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:12:15.988 [error] <0.433.0> CRASH REPORT Process <0.433.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta9/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:13:16.097 [error] <0.442.0> Supervisor vmq_swc_store_sup_meta10 had child {vmq_swc_db_leveldb,meta10} started with vmq_swc_db_leveldb:start_link({swc_config,{'VerneMQ@127.0.0.1',<<239,174,60,145,53,39,215,115,159,70,176,124,80,197,199,248,97,...>>},...}, []) at undefined exit with reason {db_open,"IO error: lock ./data/swc_meta/meta10/LOCK: Resource temporarily unavailable"} in context start_error
2023-02-15 01:13:16.098 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/swc_meta/meta10/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:14:16.288 [error] <0.458.0> CRASH REPORT Process <0.458.0> with 0 neighbours exited with reason: {db_open,"IO error: lock ./data/msgstore/1/LOCK: Resource temporarily unavailable"} in gen_server:init_it/6 line 835
2023-02-15 01:14:16.289 [error] <0.455.0>@vmq_generic_msg_store_sup:-start_link/0-lc$^0/1-0-:43 CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: no match of right hand value {error,{{db_open,"IO error: lock ./data/msgstore/1/LOCK: Resource temporarily unavailable"},{child,undefined,{vmq_generic_msg_store_bucket,1},{vmq_generic_msg_store,start_link,[1]},permanent,false,5000,worker,[vmq_generic_msg_store]}}} in vmq_generic_msg_store_sup:'-start_link/0-lc$^0/1-0-'/2 line 43 in application_master:init/4 line 142
2023-02-15 01:14:16.299 [error] <0.208.0>@vmq_plugin_mgr:start_plugin:573 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{db_open,"IO error: lock ./data/msgstore/1/LOCK: Resource temporarily unavailable"},{child,undefined,{vmq_generic_msg_store_bucket,1},{vmq_generic_msg_store,start_link,[1]},permanent,false,5000,worker,[vmq_generic_msg_store]}}}},[{vmq_generic_msg_store_sup,'-start_link/0-lc$^0/1-0-',2,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_generic_msg_store/src/vmq_generic..."},...]},...]}}}}}} in vmq_plugin_mgr:start_plugin/1 line 573
2023-02-15 01:14:16.300 [error] <0.208.0>@vmq_plugin_mgr:start_plugin:573 CRASH REPORT Process vmq_plugin_mgr with 1 neighbours crashed with reason: no match of right hand value {error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{db_open,"IO error: lock ./data/msgstore/1/LOCK: Resource temporarily unavailable"},{child,undefined,{vmq_generic_msg_store_bucket,1},{vmq_generic_msg_store,start_link,[1]},permanent,false,5000,worker,[vmq_generic_msg_store]}}}},[{vmq_generic_msg_store_sup,'-start_link/0-lc$^0/1-0-',2,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_generic_msg_store/src/vmq_generic..."},...]},...]}}}}}} in vmq_plugin_mgr:start_plugin/1 line 573
2023-02-15 01:14:16.300 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:573 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.208.0> exit with reason no match of right hand value {error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{db_open,"IO error: lock ./data/msgstore/1/LOCK: Resource temporarily unavailable"},{child,undefined,{vmq_generic_msg_store_bucket,1},{vmq_generic_msg_store,start_link,[1]},permanent,false,5000,worker,[vmq_generic_msg_store]}}}},[{vmq_generic_msg_store_sup,'-start_link/0-lc$^0/1-0-',2,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_generic_msg_store/src/vmq_generic..."},...]},...]}}}}}} in vmq_plugin_mgr:start_plugin/1 line 573 in context child_terminated
2023-02-15 01:14:16.300 [error] <0.214.0> CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: {{{badmatch,{error,{vmq_generic_msg_store,{bad_return,{{vmq_generic_msg_store_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{{db_open,"IO error: lock ./data/msgstore/1/LOCK: Resource temporarily unavailable"},{child,undefined,{vmq_generic_msg_store_bucket,1},{vmq_generic_msg_store,start_link,[1]},permanent,false,5000,worker,[vmq_generic_msg_store]}}}},[{vmq_generic_msg_store_sup,'-start_link/0-lc$^0/1-0-',2,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_generic_msg_store/s..."},...]},...]}}}}}}},...},...} in application_master:init/4 line 142
2023-02-16 21:16:12.062 [error] <0.460.0>@vmq_ranch_config:reconfigure_listeners_for_type:{269,13} can't reconfigure mqtts listener({127,0,0,1}, 1883) with Options [{max_connections,10000},{nr_of_acceptors,10},{mountpoint,[]},{depth,1},{eccs,[sect571r1,sect571k1,secp521r1,brainpoolP512r1,sect409k1,sect409r1,brainpoolP384r1,secp384r1,sect283k1,sect283r1,brainpoolP256r1,secp256k1,secp256r1,sect239k1,sect233k1,sect233r1,secp224k1,secp224r1,sect193r1,sect193r2,secp192k1,secp192r1,sect163k1,sect163r1,sect163r2,secp160k1,secp160r1,secp160r2]},{require_certificate,false},{tls_version,'tlsv1.2'},{use_identity_as_username,false},{allowed_protocol_versions,[3,4,131]},{allow_anonymous_override,false}] due to {already_started,<0.461.0>}
2023-02-16 21:16:27.388 [error] <0.208.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:16:27.388 [error] <0.208.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:16:27.388 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.208.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:17:29.537 [error] <0.604.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:17:29.537 [error] <0.604.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:17:29.537 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.604.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:20:37.462 [error] <0.617.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:20:37.462 [error] <0.617.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:20:37.462 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.617.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:29:57.348 [error] <0.642.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:29:57.348 [error] <0.642.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:29:57.348 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.642.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:34:51.785 [error] <0.706.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:34:51.785 [error] <0.706.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:34:51.785 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.706.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:40:58.178 [error] <0.745.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:40:58.178 [error] <0.745.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:40:58.178 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.745.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:56:32.632 [error] <0.789.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:56:32.632 [error] <0.789.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:56:32.632 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.789.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 21:56:35.278 [error] <0.898.0>@vmq_plugin_mgr:start_plugin:576 gen_server vmq_plugin_mgr terminated with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:56:35.278 [error] <0.898.0>@vmq_plugin_mgr:start_plugin:576 CRASH REPORT Process vmq_plugin_mgr with 0 neighbours crashed with reason: no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576
2023-02-16 21:56:35.278 [error] <0.207.0>@vmq_plugin_mgr:start_plugin:576 Supervisor vmq_plugin_sup had child vmq_plugin_mgr started with vmq_plugin_mgr:start_link() at <0.898.0> exit with reason no match of right hand value {error,{elixir,{"no such file or directory","elixir.app"}}} in vmq_plugin_mgr:start_plugin/1 line 576 in context child_terminated
2023-02-16 23:23:31.304 [error] <0.417.0>@vmq_config:get_env:111 gen_server vmq_retain_srv terminated with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111
2023-02-16 23:23:31.304 [error] <0.417.0>@vmq_config:get_env:111 CRASH REPORT Process vmq_retain_srv with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:terminate/3 line 1143
2023-02-16 23:23:31.304 [error] <0.410.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at <0.417.0> exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context child_terminated
2023-02-16 23:23:31.304 [error] <0.410.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at <0.417.0> exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.304 [error] <0.1146.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1146.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.304 [error] <0.410.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at {restarting,<0.417.0>} exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.305 [error] <0.1147.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1147.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.305 [error] <0.410.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at {restarting,<0.417.0>} exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.305 [error] <0.1148.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1148.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.305 [error] <0.410.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at {restarting,<0.417.0>} exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.305 [error] <0.1149.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1149.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.305 [error] <0.410.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at {restarting,<0.417.0>} exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.305 [error] <0.410.0> Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at {restarting,<0.417.0>} exit with reason reached_max_restart_intensity in context shutdown
2023-02-16 23:23:31.305 [error] <0.1150.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1150.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.305 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at <0.410.0> exit with reason shutdown in context child_terminated
2023-02-16 23:23:31.306 [error] <0.1151.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at undefined exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.306 [error] <0.1154.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1154.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.307 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at <0.410.0> exit with reason {'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,vmq_retain_srv,{{case_clause,{error,no_matching_hook_found}},[{vmq_config,get_env,4,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_config.erl"},{line,111}]},{vmq_retain_srv,init,1,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_retain_srv.erl"},{line,168}]},{gen_server2,init_it,6,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/_build/default/lib/gen_server2/src/gen_server2.erl"},...]},...]}}}}},...}} in context start_error
2023-02-16 23:23:31.307 [error] <0.1155.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at undefined exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.307 [error] <0.1158.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1158.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.307 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at {restarting,<0.410.0>} exit with reason {'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,vmq_retain_srv,{{case_clause,{error,no_matching_hook_found}},[{vmq_config,get_env,4,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_config.erl"},{line,111}]},{vmq_retain_srv,init,1,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_retain_srv.erl"},{line,168}]},{gen_server2,init_it,6,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/_build/default/lib/gen_server2/src/gen_server2.erl"},...]},...]}}}}},...}} in context start_error
2023-02-16 23:23:31.307 [error] <0.1159.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at undefined exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.307 [error] <0.1162.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1162.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.308 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at {restarting,<0.410.0>} exit with reason {'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,vmq_retain_srv,{{case_clause,{error,no_matching_hook_found}},[{vmq_config,get_env,4,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_config.erl"},{line,111}]},{vmq_retain_srv,init,1,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_retain_srv.erl"},{line,168}]},{gen_server2,init_it,6,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/_build/default/lib/gen_server2/src/gen_server2.erl"},...]},...]}}}}},...}} in context start_error
2023-02-16 23:23:31.308 [error] <0.1163.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at undefined exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.308 [error] <0.1166.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1166.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.342 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at {restarting,<0.410.0>} exit with reason {'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,vmq_retain_srv,{{case_clause,{error,no_matching_hook_found}},[{vmq_config,get_env,4,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_config.erl"},{line,111}]},{vmq_retain_srv,init,1,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_retain_srv.erl"},{line,168}]},{gen_server2,init_it,6,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/_build/default/lib/gen_server2/src/gen_server2.erl"},...]},...]}}}}},...}} in context start_error
2023-02-16 23:23:31.343 [error] <0.1167.0>@vmq_config:get_env:111 Supervisor vmq_reg_sup had child vmq_retain_srv started with vmq_retain_srv:start_link() at undefined exit with reason no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in context start_error
2023-02-16 23:23:31.343 [error] <0.1170.0>@vmq_config:get_env:111 CRASH REPORT Process <0.1170.0> with 0 neighbours exited with reason: no case clause matching {error,no_matching_hook_found} in vmq_config:get_env/4 line 111 in gen_server2:init_it/6 line 586
2023-02-16 23:23:31.343 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at {restarting,<0.410.0>} exit with reason {'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,vmq_retain_srv,{{case_clause,{error,no_matching_hook_found}},[{vmq_config,get_env,4,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_config.erl"},{line,111}]},{vmq_retain_srv,init,1,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/apps/vmq_server/src/vmq_retain_srv.erl"},{line,168}]},{gen_server2,init_it,6,[{file,"/Users/tejarammurthykarri/Desktop/vernemq/_build/default/lib/gen_server2/src/gen_server2.erl"},...]},...]}}}}},...}} in context start_error
2023-02-16 23:23:31.343 [error] <0.336.0> Supervisor vmq_server_sup had child vmq_reg_sup started with vmq_reg_sup:start_link() at {restarting,<0.410.0>} exit with reason reached_max_restart_intensity in context shutdown
2023-02-16 23:23:57.957 [error] <0.446.0>@vmq_ranch_config:reconfigure_listeners_for_type:{269,13} can't reconfigure mqtts listener({127,0,0,1}, 1883) with Options [{max_connections,10000},{nr_of_acceptors,10},{mountpoint,[]},{depth,1},{eccs,[sect571r1,sect571k1,secp521r1,brainpoolP512r1,sect409k1,sect409r1,brainpoolP384r1,secp384r1,sect283k1,sect283r1,brainpoolP256r1,secp256k1,secp256r1,sect239k1,sect233k1,sect233r1,secp224k1,secp224r1,sect193r1,sect193r2,secp192k1,secp192r1,sect163k1,sect163r1,sect163r2,secp160k1,secp160r1,secp160r2]},{require_certificate,false},{tls_version,'tlsv1.2'},{use_identity_as_username,false},{allowed_protocol_versions,[3,4,131]},{allow_anonymous_override,false}] due to {already_started,<0.447.0>}
